# -*- coding: utf-8 -*-
"""Copy of Copy of numpy-assignment-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Ie816R9Jz5sr1XV972VyXhwpE8D0QEf
"""

import numpy as np

arr1=np.arange(20).reshape(4,5)
arr1

# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing

arr1[:,[0,3]]=arr1[:,[3,0]]
arr1

# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row

arr1[[0,3],:]=arr1[[3,0],:]
arr1

arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

arr2=np.array([[1,2,np.mean(arr2)],[4,5,6],[np.mean(arr2),np.mean(arr2),9]])
arr2

arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3



# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

mask=arr3>25 
mask1=arr3%3==0
arr3[mask | mask1]

# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

np.percentile(arr3,[10,25,50])